### ISSUE TITLE
[Feature Request]: Allow easier repository specification in config

### ISSUE THREAD

**Issue by walkowif** [insightsengineering/locksmith#21]
### Feature description

Currently, one can specify input repositories like this in the config file:
```yaml
inputRepositories:
  - Bioconductor.BioCsoft=https://bioconductor.org/packages/release/bioc
  - CRAN=https://cran.rstudio.com
```

We could make it a bit better:
```yaml
inputRepositories:
  - name: Bioconductor.BioCsoft
    url: https://bioconductor.org/packages/release/bioc
  - name: CRAN
    url: https://cran.rstudio.com
```

This is easily doable with `viper` and is used for [git-synchronizer config](https://github.com/insightsengineering/git-synchronizer/blob/main/README.md#configuration-file).

After implementing, the `README.md` has to be updated to reflect the change.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.
