### ISSUE TITLE
[Feature Request]: Suggested UX improvements

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/locksmith#5]
### Feature description

As a user of `locksmith`, I would like the ability to specify which packages I want to test via a configuration file instead of passing a list via a CLI. 

Currently the UX looks like this:

```shell
locksmith --inputPackageList https://raw.githubusercontent.com/insightsengineering/formatters/main/DESCRIPTION,https://raw.githubusercontent.com/insightsengineering/rtables/main/DESCRIPTION,https://raw.githubusercontent.com/insightsengineering/scda/main/DESCRIPTION,https://raw.githubusercontent.com/insightsengineering/scda.2022/main/DESCRIPTION,https://raw.githubusercontent.com/insightsengineering/nestcolor/main/DESCRIPTION,https://raw.githubusercontent.com/insightsengineering/tern/main/DESCRIPTION,https://raw.githubusercontent.com/insightsengineering/rlistings/main/DESCRIPTION --inputRepositoryList BioC=https://bioconductor.org/packages/release/bioc,CRAN=https://cran.rstudio.com/
```

Instead, we'd like something that looks like this in config file:

```yaml
inputPackageList:
  - https://raw.githubusercontent.com/insightsengineering/formatters/main/DESCRIPTION
  - https://raw.githubusercontent.com/insightsengineering/rtables/main/DESCRIPTION
  ...
  - https://raw.githubusercontent.com/insightsengineering/rlistings/main/DESCRIPTION
inputRepositoryList:
  - CRAN=https://cran.rstudio.com/
  - BioC=https://bioconductor.org/packages/release/bioc
```

The original CLI args should still be supported as there may use cases where we only want to supply a few packages or repos and don't need a config file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.
